# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

GeneralSettings:
  # Amount of seconds the block glow effect lasts when the use of a locked item is denied
  blockGlowTime: 5

GuiSettings:
  # When a menu is grabbing nearby players for suggestions, this is how far it will look around the player
  nearbyPlayersRange: 100

LockItem:
  # If the lock item is enabled. All following settings this to false will make lock items do nothing
  enabled: true

  # If the default lock recipe should be enabled (loaded) when the plugin is enabled
  # If using an item plugin this will automatically be disabled
  enableCraftingRecipe: true

  # If protected blocks/entities will drop a lock item when broken
  protectionsDropLocks: true

  # What worlds players will be able to use locks in
  enabledWorlds:
    - world
    - world_nether
    - world_the_end

  # The sound made when a player creates a new protection with a lock
  sound:
    enabled: true
    effect: "minecraft:entity.zombie.attack_iron_door"
    volume: 0.25
    pitch: 1.0

  # Possible entries are "ItemsAdder", "Nexo", "Oraxen" or "None". Leave blank or use "None" to use the default lock item
  itemPlugin: ""

  # The identifier of the custom lock item. Only applicable if using an item plugin defined above
  customLockItemID: ""

  # The default lock item if no item plugin is specified
  # Uses MiniMessage color formats
  DefaultLockItem:
    material: IRON_INGOT
    customModelData: 8792
    displayName: "<gray><b>Iron Lock</b></gray>"
    lore:
      - "<yellow>Shift-Right Click to Use</yellow>"
      - "<yellow>Lockable Things: Containers, Doors, Gates, Trapdoors</yellow>"

TownyCompatibility:
  # Disable locking in towns that a player is not a part of
  disableLockingInOtherTowns: true
  # Allow Town mayors to access protections within their town claims
  allowMayorsToAccessLocked: true

QuickShopCompatibility:
  # Disable locking of QuickShop shops
  disableLockingShops: true
